# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/Marci/coding/skycow

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/Marci/coding/skycow

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	cd /home/Marci/coding/skycow && $(CMAKE_COMMAND) -E cmake_progress_start /home/Marci/coding/skycow/CMakeFiles /home/Marci/coding/skycow/fernengine//CMakeFiles/progress.marks
	cd /home/Marci/coding/skycow && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fernengine/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/Marci/coding/skycow/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/Marci/coding/skycow && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fernengine/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/Marci/coding/skycow && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fernengine/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/Marci/coding/skycow && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fernengine/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/Marci/coding/skycow && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
fernengine/CMakeFiles/fern.dir/rule:
	cd /home/Marci/coding/skycow && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fernengine/CMakeFiles/fern.dir/rule
.PHONY : fernengine/CMakeFiles/fern.dir/rule

# Convenience name for target.
fern: fernengine/CMakeFiles/fern.dir/rule
.PHONY : fern

# fast build rule for target.
fern/fast:
	cd /home/Marci/coding/skycow && $(MAKE) $(MAKESILENT) -f fernengine/CMakeFiles/fern.dir/build.make fernengine/CMakeFiles/fern.dir/build
.PHONY : fern/fast

dependencies/glad/src/gl.o: dependencies/glad/src/gl.c.o
.PHONY : dependencies/glad/src/gl.o

# target to build an object file
dependencies/glad/src/gl.c.o:
	cd /home/Marci/coding/skycow && $(MAKE) $(MAKESILENT) -f fernengine/CMakeFiles/fern.dir/build.make fernengine/CMakeFiles/fern.dir/dependencies/glad/src/gl.c.o
.PHONY : dependencies/glad/src/gl.c.o

dependencies/glad/src/gl.i: dependencies/glad/src/gl.c.i
.PHONY : dependencies/glad/src/gl.i

# target to preprocess a source file
dependencies/glad/src/gl.c.i:
	cd /home/Marci/coding/skycow && $(MAKE) $(MAKESILENT) -f fernengine/CMakeFiles/fern.dir/build.make fernengine/CMakeFiles/fern.dir/dependencies/glad/src/gl.c.i
.PHONY : dependencies/glad/src/gl.c.i

dependencies/glad/src/gl.s: dependencies/glad/src/gl.c.s
.PHONY : dependencies/glad/src/gl.s

# target to generate assembly for a file
dependencies/glad/src/gl.c.s:
	cd /home/Marci/coding/skycow && $(MAKE) $(MAKESILENT) -f fernengine/CMakeFiles/fern.dir/build.make fernengine/CMakeFiles/fern.dir/dependencies/glad/src/gl.c.s
.PHONY : dependencies/glad/src/gl.c.s

source/display.o: source/display.c.o
.PHONY : source/display.o

# target to build an object file
source/display.c.o:
	cd /home/Marci/coding/skycow && $(MAKE) $(MAKESILENT) -f fernengine/CMakeFiles/fern.dir/build.make fernengine/CMakeFiles/fern.dir/source/display.c.o
.PHONY : source/display.c.o

source/display.i: source/display.c.i
.PHONY : source/display.i

# target to preprocess a source file
source/display.c.i:
	cd /home/Marci/coding/skycow && $(MAKE) $(MAKESILENT) -f fernengine/CMakeFiles/fern.dir/build.make fernengine/CMakeFiles/fern.dir/source/display.c.i
.PHONY : source/display.c.i

source/display.s: source/display.c.s
.PHONY : source/display.s

# target to generate assembly for a file
source/display.c.s:
	cd /home/Marci/coding/skycow && $(MAKE) $(MAKESILENT) -f fernengine/CMakeFiles/fern.dir/build.make fernengine/CMakeFiles/fern.dir/source/display.c.s
.PHONY : source/display.c.s

source/fern_error.o: source/fern_error.c.o
.PHONY : source/fern_error.o

# target to build an object file
source/fern_error.c.o:
	cd /home/Marci/coding/skycow && $(MAKE) $(MAKESILENT) -f fernengine/CMakeFiles/fern.dir/build.make fernengine/CMakeFiles/fern.dir/source/fern_error.c.o
.PHONY : source/fern_error.c.o

source/fern_error.i: source/fern_error.c.i
.PHONY : source/fern_error.i

# target to preprocess a source file
source/fern_error.c.i:
	cd /home/Marci/coding/skycow && $(MAKE) $(MAKESILENT) -f fernengine/CMakeFiles/fern.dir/build.make fernengine/CMakeFiles/fern.dir/source/fern_error.c.i
.PHONY : source/fern_error.c.i

source/fern_error.s: source/fern_error.c.s
.PHONY : source/fern_error.s

# target to generate assembly for a file
source/fern_error.c.s:
	cd /home/Marci/coding/skycow && $(MAKE) $(MAKESILENT) -f fernengine/CMakeFiles/fern.dir/build.make fernengine/CMakeFiles/fern.dir/source/fern_error.c.s
.PHONY : source/fern_error.c.s

source/loader.o: source/loader.c.o
.PHONY : source/loader.o

# target to build an object file
source/loader.c.o:
	cd /home/Marci/coding/skycow && $(MAKE) $(MAKESILENT) -f fernengine/CMakeFiles/fern.dir/build.make fernengine/CMakeFiles/fern.dir/source/loader.c.o
.PHONY : source/loader.c.o

source/loader.i: source/loader.c.i
.PHONY : source/loader.i

# target to preprocess a source file
source/loader.c.i:
	cd /home/Marci/coding/skycow && $(MAKE) $(MAKESILENT) -f fernengine/CMakeFiles/fern.dir/build.make fernengine/CMakeFiles/fern.dir/source/loader.c.i
.PHONY : source/loader.c.i

source/loader.s: source/loader.c.s
.PHONY : source/loader.s

# target to generate assembly for a file
source/loader.c.s:
	cd /home/Marci/coding/skycow && $(MAKE) $(MAKESILENT) -f fernengine/CMakeFiles/fern.dir/build.make fernengine/CMakeFiles/fern.dir/source/loader.c.s
.PHONY : source/loader.c.s

source/material.o: source/material.c.o
.PHONY : source/material.o

# target to build an object file
source/material.c.o:
	cd /home/Marci/coding/skycow && $(MAKE) $(MAKESILENT) -f fernengine/CMakeFiles/fern.dir/build.make fernengine/CMakeFiles/fern.dir/source/material.c.o
.PHONY : source/material.c.o

source/material.i: source/material.c.i
.PHONY : source/material.i

# target to preprocess a source file
source/material.c.i:
	cd /home/Marci/coding/skycow && $(MAKE) $(MAKESILENT) -f fernengine/CMakeFiles/fern.dir/build.make fernengine/CMakeFiles/fern.dir/source/material.c.i
.PHONY : source/material.c.i

source/material.s: source/material.c.s
.PHONY : source/material.s

# target to generate assembly for a file
source/material.c.s:
	cd /home/Marci/coding/skycow && $(MAKE) $(MAKESILENT) -f fernengine/CMakeFiles/fern.dir/build.make fernengine/CMakeFiles/fern.dir/source/material.c.s
.PHONY : source/material.c.s

source/model.o: source/model.c.o
.PHONY : source/model.o

# target to build an object file
source/model.c.o:
	cd /home/Marci/coding/skycow && $(MAKE) $(MAKESILENT) -f fernengine/CMakeFiles/fern.dir/build.make fernengine/CMakeFiles/fern.dir/source/model.c.o
.PHONY : source/model.c.o

source/model.i: source/model.c.i
.PHONY : source/model.i

# target to preprocess a source file
source/model.c.i:
	cd /home/Marci/coding/skycow && $(MAKE) $(MAKESILENT) -f fernengine/CMakeFiles/fern.dir/build.make fernengine/CMakeFiles/fern.dir/source/model.c.i
.PHONY : source/model.c.i

source/model.s: source/model.c.s
.PHONY : source/model.s

# target to generate assembly for a file
source/model.c.s:
	cd /home/Marci/coding/skycow && $(MAKE) $(MAKESILENT) -f fernengine/CMakeFiles/fern.dir/build.make fernengine/CMakeFiles/fern.dir/source/model.c.s
.PHONY : source/model.c.s

source/shader.o: source/shader.c.o
.PHONY : source/shader.o

# target to build an object file
source/shader.c.o:
	cd /home/Marci/coding/skycow && $(MAKE) $(MAKESILENT) -f fernengine/CMakeFiles/fern.dir/build.make fernengine/CMakeFiles/fern.dir/source/shader.c.o
.PHONY : source/shader.c.o

source/shader.i: source/shader.c.i
.PHONY : source/shader.i

# target to preprocess a source file
source/shader.c.i:
	cd /home/Marci/coding/skycow && $(MAKE) $(MAKESILENT) -f fernengine/CMakeFiles/fern.dir/build.make fernengine/CMakeFiles/fern.dir/source/shader.c.i
.PHONY : source/shader.c.i

source/shader.s: source/shader.c.s
.PHONY : source/shader.s

# target to generate assembly for a file
source/shader.c.s:
	cd /home/Marci/coding/skycow && $(MAKE) $(MAKESILENT) -f fernengine/CMakeFiles/fern.dir/build.make fernengine/CMakeFiles/fern.dir/source/shader.c.s
.PHONY : source/shader.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... fern"
	@echo "... dependencies/glad/src/gl.o"
	@echo "... dependencies/glad/src/gl.i"
	@echo "... dependencies/glad/src/gl.s"
	@echo "... source/display.o"
	@echo "... source/display.i"
	@echo "... source/display.s"
	@echo "... source/fern_error.o"
	@echo "... source/fern_error.i"
	@echo "... source/fern_error.s"
	@echo "... source/loader.o"
	@echo "... source/loader.i"
	@echo "... source/loader.s"
	@echo "... source/material.o"
	@echo "... source/material.i"
	@echo "... source/material.s"
	@echo "... source/model.o"
	@echo "... source/model.i"
	@echo "... source/model.s"
	@echo "... source/shader.o"
	@echo "... source/shader.i"
	@echo "... source/shader.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/Marci/coding/skycow && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

